name: Manual trigger
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
   workflow_dispatch:
     inputs: 
       Preferdfood:
         description: "Your favourite food"
         type: choice
         default: "sushi"
         options: 
           - "Sushi"
           - "Pizza"
           - "Pasta"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Saar is the best teacher in the world and i am in love with him, he is my king forever <3"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Read start.txt and show CPU of github runner
      - run: |
        lscpu
      - run: cat '/home/runner/work/github-demo/github-demo/start.txt'
    












