name: My-first-GithubActions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 My first workflow"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Read start.txt
        run: cat '/home/runner/work/github-demo/github-demo/start.txt'
    

